version: "3"
services:
  postgresql:
    image: postgres:16
    container_name: project-postgresql
    ports:
      - "25432:5432"
    volumes:
      - postgresql-db:/var/lib/postgresql/data
    environment:
      PGRST_DB_SCHEMA: public
      PGRST_AUTHENTICATOR_PASSWORD: 123456
      POSTGRES_DB: project
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped
    logging:
      options:
        max-size: 100m
        max-file: "5"

volumes:
  postgresql-db:
    driver: local
